# Generated by Django 5.2.4 on 2025-08-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_favoritearticle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritearticle',
            unique_together=set(),
        ),
    ]
